# Generated by Django 3.2 on 2024-09-20 17:58

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_job_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326),
        ),
    ]
